runtime: custom
api_version: 1
threadsafe: true 
vm: true

manual_scaling:
  instances: 1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /img
  static_dir: static/img

- url: /phaselist.json
  static_files: phaselist.json
  upload: phaselist.json
  application_readable: true

- url: /.*
  script: quantdatavision.app
  login: required

skip_files:
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*desktop/.*$

