runtime: custom
api_version: 1
threadsafe: true 
vm: true

manual_scaling:
  instances: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /assets
  static_dir: templates/assets

- url: /phaselist.json
  static_files: phaselist.json
  upload: phaselist.json
  application_readable: true

- url: /.*
  script: quantdatavision.app
  login: required

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
