runtime: custom
api_version: 1
threadsafe: true 
vm: true

manual_scaling:
  instances: 1

resources:
  cpu: 1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /img
  static_dir: static/img

- url: /.*
  script: quantdatavision.app

skip_files:
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*desktop/.*$
- ^(.*/)?.*shelf/.*$
