runtime: custom
api_version: 1
threadsafe: true 
vm: true

manual_scaling:
  instances: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /phaselist.json
  static_files: phaselist.json
  upload: phaselist.json
  application_readable: true

- url: /.*
  script: quantdatavision.app
